CREATE DATABASE driver_log_db;
USE driver_log_db;

CREATE TABLE DRIVER_LOG (
  ID              INT AUTO_INCREMENT PRIMARY KEY,
  DRIVER_NAME     VARCHAR(200)   NOT NULL,
  PURPOSE         VARCHAR(500)   NOT NULL,
  VEHICLE_TYPE    VARCHAR(100)   NOT NULL,
  VEHICLE_NUMBER  VARCHAR(100)   NOT NULL,
  IN_TIME         DATETIME       NOT NULL,
  OUT_TIME        DATETIME       NOT NULL,
  TIME_DIFFERENCE VARCHAR(50),
  IN_KM           DECIMAL(10,2)  NOT NULL,
  OUT_KM          DECIMAL(10,2)  NOT NULL,
  KM_DIFFERENCE   DECIMAL(10,2),
  CREATED_AT      DATETIME       DEFAULT CURRENT_TIMESTAMP
);




CREATE TABLE USERS (
  ID         INT AUTO_INCREMENT PRIMARY KEY,
  FULL_NAME  VARCHAR(200) NOT NULL,
  USERNAME   VARCHAR(100) NOT NULL UNIQUE,
  EMAIL      VARCHAR(200) NOT NULL UNIQUE,
  PASSWORD   VARCHAR(255) NOT NULL,
  CREATED_AT DATETIME     DEFAULT CURRENT_TIMESTAMP
);